apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot
    app.kubernetes.io/part-of: appstudio
  name: java-springboot
  namespace: 529b6595-76a8-4cdd-97b7-53ab9aa54916
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: java-springboot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: java-springboot
    spec:
      containers:
      - image: quay.io/damoreno/foobar:dev-code-with-quarkus
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
