apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot
    app.kubernetes.io/part-of: appstudio
  name: java-springboot
  namespace: 529b6595-76a8-4cdd-97b7-53ab9aa54916
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-springboot
    weight: 100
status: {}
